-- Manuel Delgado
-- Base de Datos
-- COMERCIAL

CREATE DATABASE COMERCIAL;
USE COMERCIAL;

CREATE TABLE COMERCIAL
(
ID INT,
NOMBRE VARCHAR(100),
APELLIDO1 VARCHAR(100),
APELLIDO2 VARCHAR(100),
COMISION FLOAT
);

CREATE TABLE CLIENTE	
(
ID INT,
NOMBRE VARCHAR(100),
APELLIDO1 VARCHAR(100),
APELLIDO2 VARCHAR(100),
CIUDAD VARCHAR(100),
CATEGORIA INT
);